spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:mysql://localhost:3306/pet?characterEncoding=UTF-8&serverTimezone=UCT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    primary:
#      hikari:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: 1234
#        jdbc-url: jdbc:mysql://localhost:3306/pet?characterEncoding=UTF-8&serverTimezone=UCT
#    secondary:
#      hikari:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: 1234
#        jdbc-url: jdbc:mysql://localhost:3306/pet?characterEncoding=UTF-8&serverTimezone=UCT
#    hikari:
#      pool-name: Hikari
#      auto-commit: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL57Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    open-in-view: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  token:
    header-type: JWT
    header: Authorization
    secret: ENC(96CvoYH1HnbpIxw7kLXaESwEcgB92xTiloPB5QoFCGFL4fWEIsCxbpoCYoqCxgSGp7Umj9C6mnUjh99cPEGM8RYzcVF5v+82G2Wos2xsyUtMZh/ZITZzh0R74NtoS6ma7G4UjHECfIfMdpiFQuDJMg1JKcXurOP2rSHGxdTTSFs=)
    access-time: 604800000 # 7일
    refresh-time: 2628000000 # 한달
    issuer: yapp

springdoc:
  api-docs:
    path: /api-docs
    enabled: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method // alpha or mehod
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    url: /openapi.yml
  paths-to-match:
    - /api/**
    - /auth/**

social:
    kakao:
      client-id: ENC(3eXLqoML65d+7ezHZVOy7qMtQXKnKv2QW9Wj1mlqQjC9xN2VDtl24v8qa9jyLjNj)
      client-secret: ENC(0R1l0yX0YP1IyTGIRN8ONkKnlgLJyRMntgV5PLYdBhNwP/dCmTudb55tm49tGTvg)

cloud:
  aws:
    s3:
      bucket: togaether
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
      access-key: ENC(SyQn0StyUrPZlDyfMv2oRmhwu+aXPfu0jLZ4+Yn+1n0=)
      secret-key: ENC(Ynei80LW10nIFe4iuc9MI+xGiGsW5MyVI1Zvb51yzYs0UnxktFIgVd0KNpY8fo7hTjXQvRwPr9E=)

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE

TOGATHER_PRIVATE_IP : ENC(kRhINLnICycy74s94393nGaUq+fUBrzS)