spring:
  datasource:
    url: ENC(6i1jdQipg+rwi3HjMLT/XwqtNWgdeABWKPbWRIpKXoJPPkwzC5jWioweN6n7Oin/jdEBhLsCkDBhf/VFMkUOlP/HOx3RLdaK0JYYU+KPrk2Iaw3rJE9gHA==)
    username: ENC(OTUfXu9X9QBk4lG0mm19+A==)
    password: ENC(8d+CPaIyBQOntW/l/k6WlE9NqDqx5eoR)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.MySQL5InnoDBDialect

jasypt:
  encryptor:
    bean: jasyptStringEncryptor