spring:
  datasource:
    url: ENC(zwJFK8HCOJbOI+PMINipGtjyA8QrfgSebqpEx84L/IsZtceoeff+Wk/cksUiesNLmn86NjlZge7YD9kZrGJFo5KIKYcuxvcyfhQeyjMNLRtZ+G0Ef7dNLDEoJiKPkskGcPTOwjZR2Pmy6UWShrNg8g==)
    username: ENC(OTUfXu9X9QBk4lG0mm19+A==)
    password: ENC(8d+CPaIyBQOntW/l/k6WlE9NqDqx5eoR)
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL57Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.MySQL5InnoDBDialect

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

springdoc:
  version: '1.0'
  api-docs:
    path: /api-docs
    enabled: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    url: /openapi.yml
  paths-to-match:
    - /api/**
    - /auth/**

jwt:
  token:
    header-type: JWT
    header: Authorization
    secret: ENC(96CvoYH1HnbpIxw7kLXaESwEcgB92xTiloPB5QoFCGFL4fWEIsCxbpoCYoqCxgSGp7Umj9C6mnUjh99cPEGM8RYzcVF5v+82G2Wos2xsyUtMZh/ZITZzh0R74NtoS6ma7G4UjHECfIfMdpiFQuDJMg1JKcXurOP2rSHGxdTTSFs=)
    access-time: 604800000 # 7일
    refresh-time: 2628000000 # 한달
    issuer: yapp

social:
  kakao:
    client-id: ENC(3eXLqoML65d+7ezHZVOy7qMtQXKnKv2QW9Wj1mlqQjC9xN2VDtl24v8qa9jyLjNj)
    client-secret: ENC(0R1l0yX0YP1IyTGIRN8ONkKnlgLJyRMntgV5PLYdBhNwP/dCmTudb55tm49tGTvg)

cloud:
  aws:
    s3:
      bucket: togaether
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
      access-key: ENC(SyQn0StyUrPZlDyfMv2oRmhwu+aXPfu0jLZ4+Yn+1n0=)
      secret-key: ENC(Ynei80LW10nIFe4iuc9MI+xGiGsW5MyVI1Zvb51yzYs0UnxktFIgVd0KNpY8fo7hTjXQvRwPr9E=)

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

TOGATHER_PRIVATE_IP: ENC(PwAVCI8qx/LF0pyNZptsUVdiAdV41QO+)