spring:
  datasource:
    url: jdbc:mysql://yapp-20-be.cy7tcir4lv85.ap-northeast-2.rds.amazonaws.com:3306/yapp
    username: ENC(OTUfXu9X9QBk4lG0mm19+A==)
    password: ENC(8d+CPaIyBQOntW/l/k6WlE9NqDqx5eoR)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.MySQL5InnoDBDialect

jasypt:
  encryptor:
    bean: jasyptStringEncryptor